# Idea from https://github.com/watersalesman/docker-images/tree/master/debian-metasploit
# Basically the same thing but compressed the Metasploit layer and added some cleanup to reduce size
# Note that the cleanup process breaks msfupdate functionality

FROM debian:stable

ENV LC_ALL C.UTF-8
ENV STAGING_KEY=RANDOM
ENV DEBIAN_FRONTEND noninteractive

# Apt packages to install
ENV PACKAGES "apt-utils \
        curl \
        git-core \
        libxml2 \
        openssl \
        postgresql \
        postgresql-contrib \
        ruby \
        wget \
        zlib1g"

# Apt packages to install and remove at end
ENV PACKAGES_TEMP "autoconf \
        bison \
        build-essential \
        libapr1 \
        libaprutil1 \
        libcurl4-openssl-dev \
        libgmp3-dev \
        libpcap-dev \
        libpq-dev \
        libreadline6-dev \
        libsqlite3-dev \
        libssl-dev \
        libsvn1 \
        libtool \
        libxml2-dev \
        libxslt-dev \
        libyaml-dev \
        locate \
        ncurses-dev \
        ruby-dev \
        xsel \
        zlib1g-dev"

WORKDIR /opt/

RUN apt-get -y update && \
    apt-get install -y $PACKAGES && \
    apt-get install -y $PACKAGES_TEMP && \
    git clone --depth=1 https://github.com/rapid7/metasploit-framework /opt/metasploit && \
    gem install os bundler && \
    git config --global user.name 'msf' && git config --global user.email 'msf@example.org' && \
    cd /opt/metasploit && bundler install && ./msfupdate && \
    ln -sf /opt/metasploit/msf* /usr/bin/ && \
    rm -rf /opt/metasploit/.git && \
    apt-get remove -y -f $PACKAGES_TEMP && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV MSF_RPC_USER='admin' \
    MSF_RPC_PASS='changeyourpassword' \
    MSF_RPC_PORT='55553' \
    MSF_DB='msf' \
    MSF_DB_HOST='127.0.0.1' \
    MSF_DB_PORT='5432' \
    MSF_DB_USER='msf' \
    MSF_DB_PASS='msfdb' \
    MSF_LHOST='0.0.0.0' \
    MSF_LPORT='8443'

# Configure postgres
RUN /etc/init.d/postgresql start && \
    su postgres -c 'echo -e "$MSF_DB_PASS\n$MSF_DB_PASS" | createuser -SRPD $MSF_DB_USER' && \
    su postgres -c 'createdb -O $MSF_DB_USER $MSF_DB'

ADD msfconsole-min.sh /opt/msfconsole-min.sh
ADD msfconsole.rc /opt/msfconsole.rc

WORKDIR /opt/metasploit/

CMD ["/bin/bash"]

