#!/bin/bash
set -ueo pipefail

# stolen from https://medium.com/microscaling-systems/labelling-automated-builds-on-docker-hub-f3d073fb8e1
docker build --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
             --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
             --pull -t isaudits/msf:base .
docker build -t isaudits/msf:full -t isaudits/msf:latest -f Dockerfile.full .
docker build -t isaudits/msf:minimal -f Dockerfile.min .